name: beat_pads
description: AXYP-powered mobile instrument and FL Studio companion
publish_to: "none"
version: 1.6.1+141

environment:
  sdk: ">=3.12.0 <4.0.0"
  flutter: ^3.44.0

dependencies:
  flutter:
    sdk: flutter

  flutter_midi_command:
    ^1.0.8
    # path: /Users/anz/localDev/FlutterMidiCommand
    # git:
    #   url: https://github.com/InvisibleWrench/FlutterMidiCommand.git
    #   ref: master

  flutter_riverpod: ^2.6.1
  flutter_soloud: ^5.1.5
  shared_preferences: ^2.5.3

dev_dependencies:
  # austerity: ^1.0.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  # very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
